
ALTER TABLE public.meals ALTER COLUMN lunch DROP DEFAULT;
ALTER TABLE public.meals ALTER COLUMN dinner DROP DEFAULT;
ALTER TABLE public.meals ALTER COLUMN lunch TYPE integer USING (CASE WHEN lunch THEN 1 ELSE 0 END);
ALTER TABLE public.meals ALTER COLUMN dinner TYPE integer USING (CASE WHEN dinner THEN 1 ELSE 0 END);
ALTER TABLE public.meals ALTER COLUMN lunch SET DEFAULT 0;
ALTER TABLE public.meals ALTER COLUMN dinner SET DEFAULT 0;
